DROP TABLE IF EXISTS MEMBER;
CREATE TABLE MEMBER
(
    ID       INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL
);

INSERT INTO MEMBER (USERNAME, PASSWORD)
VALUES ('user1', 'pass1');

DROP TABLE IF EXISTS POST;
CREATE TABLE POST
(
    ID        INT PRIMARY KEY AUTO_INCREMENT,
    TITLE     VARCHAR(100) NOT NULL,
    CONTENT   TEXT         NOT NULL,
    MEMBER_ID INT          NOT NULL,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID)
);

INSERT INTO POST (TITLE, CONTENT, MEMBER_ID)
VALUES ('title1', 'content1', 1);
INSERT INTO POST (TITLE, CONTENT, MEMBER_ID)
VALUES ('title2', 'content2', 1);
INSERT INTO POST (TITLE, CONTENT, MEMBER_ID)
VALUES ('title3', 'content3', 1);

DROP TABLE IF EXISTS COMMENT;
CREATE TABLE COMMENT
(
    ID        INT PRIMARY KEY AUTO_INCREMENT,
    CONTENT   TEXT NOT NULL,
    MEMBER_ID INT  NOT NULL,
    POST_ID   INT  NOT NULL,
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID),
    FOREIGN KEY (POST_ID) REFERENCES POST (ID)
);

INSERT INTO COMMENT (CONTENT, MEMBER_ID, POST_ID)
VALUES ('comment1-1', 1, 1);
INSERT INTO COMMENT (CONTENT, MEMBER_ID, POST_ID)
VALUES ('comment1-2', 1, 1);
INSERT INTO COMMENT (CONTENT, MEMBER_ID, POST_ID)
VALUES ('comment1-3', 1, 1);

INSERT INTO COMMENT (CONTENT, MEMBER_ID, POST_ID)
VALUES ('comment2-1', 1, 2);
INSERT INTO COMMENT (CONTENT, MEMBER_ID, POST_ID)
VALUES ('comment2-2', 1, 2);
INSERT INTO COMMENT (CONTENT, MEMBER_ID, POST_ID)
VALUES ('comment2-3', 1, 2);

INSERT INTO COMMENT (CONTENT, MEMBER_ID, POST_ID)
VALUES ('comment3-1', 1, 3);
INSERT INTO COMMENT (CONTENT, MEMBER_ID, POST_ID)
VALUES ('comment3-2', 1, 3);
INSERT INTO COMMENT (CONTENT, MEMBER_ID, POST_ID)
VALUES ('comment3-3', 1, 3);

